#!/usr/bin/env python3
"""Build a uniform direct-motor URDF library for every registered hand.

The output actuation grammar has exactly two movable-joint classes:

* active: an independent direct actuator, represented by a SimpleTransmission;
* passive: an affine mimic of one active joint.

There are no unconstrained passive joints.  URDF mimic relations are retained
and flattened.  MJCF joint equalities become affine mimics.  A tendon acting
on several joints is approximated by one active master and range-normalized
mimic followers.  The original assets are never modified.
"""

from __future__ import annotations

import argparse
import json
import math
import os
import shutil
import sys
import xml.etree.ElementTree as ET
from collections import defaultdict
from copy import deepcopy
from pathlib import Path

import mujoco
import numpy as np
import trimesh
from scipy.spatial.transform import Rotation


ROOT = Path(__file__).resolve().parents[2]
ASSETS = ROOT / "assets" / "robot_hands"
REGISTRY = ASSETS / "registry.json"
OUTPUT_ROOT = ASSETS / "direct_motor"
OUTPUT_REGISTRY = OUTPUT_ROOT / "registry.json"
AUDIT_PATH = OUTPUT_ROOT / "conversion_audit.json"
README_PATH = OUTPUT_ROOT / "README.md"

SIDES = ("left", "right")
MOVABLE_URDF_TYPES = {"revolute", "continuous", "prismatic"}
DEFAULT_EFFORT = 1.0
DEFAULT_ANGULAR_VELOCITY = 8.0
DEFAULT_LINEAR_VELOCITY = 1.0
MAX_IMPORT_MESH_FACES = 180_000
VISUAL_MESH_COLLISION_HANDS = {"mano"}

# Native USD assets in the current registry also ship a vendor-derived URDF.
# A future USD-only hand must provide an explicit URDF/MJCF conversion source;
# silently reconstructing a joint tree from arbitrary USD composition arcs is
# deliberately unsupported.
URDF_COMPANIONS = {
    "sharpa_wave_01": {
        "left": ASSETS / "sharpa_wave_01/models/left.urdf",
        "right": ASSETS / "sharpa_wave_01/models/right.urdf",
    },
    "tesollo_dg5f": {
        "left": ASSETS / "tesollo_dg5f/models/left.urdf",
        "right": ASSETS / "tesollo_dg5f/models/right.urdf",
    },
}


DIRECT_MOTOR_README = """# Direct-Motor Hand Assets

This directory is generated by:

```bash
python scripts/assets/build_direct_motor_hands.py
```

The generated URDFs use exactly two movable-joint classes:

- **active DoF**: an independently controlled direct motor, represented by a
  URDF `transmission`;
- **passive DoF**: an affine `mimic` follower of one active joint.

There are no unconstrained passive movable joints. Tendons, nonlinear
linkages, and mimic chains are not present in the generated representation.
The source assets under `assets/robot_hands` are never overwritten.

## Output layout

```text
direct_motor/
  registry.json
  conversion_audit.json
  overview_right_hands.png
  <hand_id>/<left|right>/hand.urdf
  <hand_id>/<left|right>/meshes/*.obj
```

Visual and collision meshes are materialized beside each URDF. For MANO, the
actual per-link hand visual meshes are reused as collision meshes; SPIDER's
extra capsule/box collision proxies are deliberately excluded. Mesh faces are
preserved rather than decimated; very large meshes are split into OBJ chunks
only to keep individual importer inputs manageable.

## Conversion rules

- Native URDF: preserve the complete link/joint tree, joint frames, axes,
  ranges, inertials, visuals, and collisions. Existing mimic relations are
  flattened to point directly at an active master.
- MJCF direct actuator: convert the controlled scalar joint to active.
- MJCF linear joint equality: convert the follower to an affine URDF mimic.
- MJCF tendon: choose one original joint as the active master and convert the
  other participating joints to range-normalized affine mimics. This removes
  contact-dependent tendon differential motion and is therefore deliberately
  recorded as a lossy actuation approximation.
- Any remaining movable source joint is promoted to active. Human/MANO joints
  are therefore all active.
- Published URDF effort limits are preserved. When missing, the audit records
  whether the value came from an MJCF actuator range, a stiffness/range proxy,
  or a conservative default.

USD-only import is intentionally unsupported. A registered USD asset must
provide an explicit URDF companion so that joint semantics are not guessed.

## Adding a future hand

1. Add bilateral entries to `assets/robot_hands/registry.json`.
2. Supply URDF or MJCF sources and all referenced meshes. For USD, also add an
   explicit companion mapping in `URDF_COMPANIONS`.
3. Rebuild this directory.
4. Run:

```bash
python scripts/assets/test_direct_motor_hands.py
```

The validation rejects missing meshes, missing joint ranges, loose movable
joints, passive joints whose master is not active, and assets that MuJoCo
cannot compile.

`registry.json` is the machine-readable entry point. `conversion_audit.json`
contains per-joint actuation, range, effort provenance, source coupling, mesh,
and repair details.
"""


def fmt(values: np.ndarray | list[float] | tuple[float, ...]) -> str:
    return " ".join(f"{float(value):.12g}" for value in values)


def safe_name(value: str) -> str:
    return "".join(character if character.isalnum() or character == "_" else "_" for character in value)


def quat_wxyz_to_rpy(quaternion: np.ndarray) -> np.ndarray:
    quaternion = np.asarray(quaternion, dtype=float)
    return Rotation.from_quat(
        [quaternion[1], quaternion[2], quaternion[3], quaternion[0]]
    ).as_euler("xyz")


def scalar_dofs_urdf(joint_type: str) -> int:
    if joint_type in MOVABLE_URDF_TYPES:
        return 1
    if joint_type == "planar":
        return 3
    if joint_type == "floating":
        return 6
    return 0


def resolve_urdf_mesh(source_dir: Path, filename: str) -> Path:
    if filename.startswith("file://"):
        return Path(filename[7:]).resolve()
    if filename.startswith("package://"):
        suffix = filename[len("package://") :]
        candidates = [
            source_dir / suffix,
            source_dir.parent / suffix,
            source_dir / suffix.split("/", 1)[-1] if "/" in suffix else source_dir / suffix,
        ]
        for candidate in candidates:
            if candidate.exists():
                return candidate.resolve()
        matches = list(ASSETS.rglob(Path(suffix).name))
        if len(matches) == 1:
            return matches[0].resolve()
        raise FileNotFoundError(f"Cannot resolve URDF package mesh {filename!r} from {source_dir}")
    return (source_dir / filename).resolve()


def load_complete_mesh(path: Path) -> trimesh.Trimesh:
    loaded = trimesh.load(path, force="scene", process=False)
    if isinstance(loaded, trimesh.Scene):
        mesh = loaded.to_geometry()
    elif isinstance(loaded, trimesh.Trimesh):
        mesh = loaded
    else:
        raise TypeError(f"Unsupported mesh {path}: {type(loaded).__name__}")
    if mesh.is_empty:
        raise ValueError(f"Empty mesh: {path}")
    mesh.remove_unreferenced_vertices()
    return mesh


def materialize_urdf_meshes(
    robot: ET.Element,
    source_dir: Path,
    output_dir: Path,
) -> tuple[int, list[str], int, int]:
    """Convert every referenced mesh to self-contained, un-decimated OBJ chunks."""
    mesh_dir = output_dir / "meshes"
    mesh_dir.mkdir(parents=True, exist_ok=True)
    cache: dict[Path, list[str]] = {}
    missing: list[str] = []
    original_faces = 0
    output_faces = 0

    def converted(path: Path) -> list[str]:
        nonlocal original_faces, output_faces
        path = path.resolve()
        if path in cache:
            return cache[path]
        mesh = load_complete_mesh(path)
        original_faces += int(len(mesh.faces))
        names: list[str] = []
        face_ids = np.arange(len(mesh.faces), dtype=np.int64)
        chunks = [
            face_ids[start : start + MAX_IMPORT_MESH_FACES]
            for start in range(0, len(face_ids), MAX_IMPORT_MESH_FACES)
        ]
        stem = f"{len(cache):04d}_{safe_name(path.stem)}"
        for index, ids in enumerate(chunks):
            chunk = mesh.submesh([ids], append=True, repair=False)
            chunk.remove_unreferenced_vertices()
            name = f"{stem}_{index:02d}.obj"
            chunk.export(
                mesh_dir / name,
                file_type="obj",
                include_normals=True,
                include_color=False,
            )
            names.append(f"meshes/{name}")
            output_faces += int(len(chunk.faces))
        cache[path] = names
        return names

    for link in robot.findall("link"):
        for tag in ("visual", "collision"):
            elements = list(link.findall(tag))
            for element in elements:
                geometry = element.find("geometry")
                mesh_node = geometry.find("mesh") if geometry is not None else None
                if mesh_node is None:
                    continue
                filename = mesh_node.get("filename")
                if not filename:
                    continue
                path = resolve_urdf_mesh(source_dir, filename)
                if not path.exists():
                    missing.append(str(path))
                    continue
                names = converted(path)
                mesh_node.set("filename", names[0])
                for chunk_index, name in enumerate(names[1:], start=1):
                    clone = deepcopy(element)
                    element_name = element.get("name", f"{link.get('name')}_{tag}")
                    clone.set(
                        "name",
                        f"{element_name}__chunk_{chunk_index}",
                    )
                    clone_geometry = clone.find("geometry")
                    assert clone_geometry is not None
                    clone_mesh = clone_geometry.find("mesh")
                    assert clone_mesh is not None
                    clone_mesh.set("filename", name)
                    link.append(clone)
    return sum(len(names) for names in cache.values()), missing, original_faces, output_faces


def joint_limit_values(joint: ET.Element) -> tuple[float, float, float, float, str]:
    kind = joint.get("type", "fixed")
    limit = joint.find("limit")
    if limit is None:
        limit = ET.SubElement(joint, "limit")
    if kind == "continuous":
        lower, upper = -math.pi, math.pi
    else:
        lower = float(limit.get("lower", "-3.141592653589793"))
        upper = float(limit.get("upper", "3.141592653589793"))
        limit.set("lower", f"{lower:.12g}")
        limit.set("upper", f"{upper:.12g}")
    effort_source = "source"
    if limit.get("effort") is None or float(limit.get("effort", "0")) <= 0:
        limit.set("effort", f"{DEFAULT_EFFORT:.12g}")
        effort_source = "default"
    effort = float(limit.get("effort", DEFAULT_EFFORT))
    if limit.get("velocity") is None or float(limit.get("velocity", "0")) <= 0:
        default_velocity = (
            DEFAULT_LINEAR_VELOCITY if kind == "prismatic" else DEFAULT_ANGULAR_VELOCITY
        )
        limit.set("velocity", f"{default_velocity:.12g}")
    velocity = float(limit.get("velocity"))
    return lower, upper, effort, velocity, effort_source


def sanitize_urdf_inertias(robot: ET.Element) -> list[dict]:
    """Repair only non-physical source inertia tensors, preserving valid ones."""
    repairs: list[dict] = []
    for link in robot.findall("link"):
        inertia = link.find("inertial/inertia")
        if inertia is None:
            continue
        matrix = np.asarray(
            [
                [
                    float(inertia.get("ixx", "0")),
                    float(inertia.get("ixy", "0")),
                    float(inertia.get("ixz", "0")),
                ],
                [
                    float(inertia.get("ixy", "0")),
                    float(inertia.get("iyy", "0")),
                    float(inertia.get("iyz", "0")),
                ],
                [
                    float(inertia.get("ixz", "0")),
                    float(inertia.get("iyz", "0")),
                    float(inertia.get("izz", "0")),
                ],
            ],
            dtype=float,
        )
        eigenvalues = np.linalg.eigvalsh(matrix)
        principal = np.sort(eigenvalues)
        physically_valid = (
            np.all(eigenvalues > 1.0e-15)
            and principal[2] <= principal[0] + principal[1] + 1.0e-12
        )
        if physically_valid:
            continue
        # Invalid public URDFs most often contain cross terms with a missing
        # exponent.  Keep their positive diagonal moments, remove the corrupt
        # products of inertia, and enforce the rigid-body triangle inequality.
        diagonal = np.maximum(np.diag(matrix), 1.0e-10)
        largest = int(np.argmax(diagonal))
        other_sum = float(np.sum(diagonal) - diagonal[largest])
        if diagonal[largest] > other_sum:
            diagonal[largest] = max(0.999 * other_sum, 1.0e-10)
        repaired = np.diag(diagonal)
        inertia.attrib.update(
            {
                "ixx": f"{repaired[0, 0]:.12g}",
                "ixy": "0",
                "ixz": "0",
                "iyy": f"{repaired[1, 1]:.12g}",
                "iyz": "0",
                "izz": f"{repaired[2, 2]:.12g}",
            }
        )
        repairs.append(
            {
                "link": link.get("name"),
                "source_matrix": matrix.tolist(),
                "repaired_matrix": repaired.tolist(),
                "reason": "non-positive or triangle-inequality-violating inertia",
            }
        )
    return repairs


def flatten_mimics(joints: dict[str, ET.Element]) -> dict[str, tuple[str, float, float]]:
    raw: dict[str, tuple[str, float, float]] = {}
    for name, joint in joints.items():
        mimic = joint.find("mimic")
        if mimic is None:
            continue
        target = mimic.get("joint")
        if not target or target not in joints:
            raise ValueError(f"{name}: mimic target {target!r} is missing")
        raw[name] = (
            target,
            float(mimic.get("multiplier", "1")),
            float(mimic.get("offset", "0")),
        )

    flattened: dict[str, tuple[str, float, float]] = {}

    def resolve(name: str, stack: tuple[str, ...] = ()) -> tuple[str, float, float]:
        if name not in raw:
            return name, 1.0, 0.0
        if name in stack:
            raise ValueError(f"Mimic cycle: {' -> '.join((*stack, name))}")
        target, multiplier, offset = raw[name]
        master, parent_multiplier, parent_offset = resolve(target, (*stack, name))
        return (
            master,
            multiplier * parent_multiplier,
            multiplier * parent_offset + offset,
        )

    for name in raw:
        flattened[name] = resolve(name)
    return flattened


def remove_existing_transmissions(robot: ET.Element) -> int:
    removed = 0
    for node in list(robot):
        if node.tag == "transmission":
            robot.remove(node)
            removed += 1
    return removed


def add_simple_transmission(robot: ET.Element, joint_name: str) -> None:
    transmission = ET.SubElement(
        robot, "transmission", {"name": f"direct_motor__{safe_name(joint_name)}"}
    )
    ET.SubElement(transmission, "type").text = "transmission_interface/SimpleTransmission"
    joint = ET.SubElement(transmission, "joint", {"name": joint_name})
    ET.SubElement(joint, "hardwareInterface").text = "hardware_interface/EffortJointInterface"
    actuator = ET.SubElement(
        transmission, "actuator", {"name": f"motor__{safe_name(joint_name)}"}
    )
    ET.SubElement(actuator, "hardwareInterface").text = "hardware_interface/EffortJointInterface"
    ET.SubElement(actuator, "mechanicalReduction").text = "1"


def add_mujoco_urdf_options(robot: ET.Element) -> None:
    """Keep relative mesh directories when MuJoCo imports the generated URDF."""
    for existing in list(robot.findall("mujoco")):
        robot.remove(existing)
    extension = ET.SubElement(robot, "mujoco")
    ET.SubElement(
        extension,
        "compiler",
        {
            "strippath": "false",
            "discardvisual": "false",
            "balanceinertia": "true",
        },
    )


def add_negligible_virtual_inertial(link: ET.Element) -> None:
    """Make scalar-expansion frame links acceptable to strict URDF importers."""
    inertial = ET.SubElement(link, "inertial")
    ET.SubElement(inertial, "origin", {"xyz": "0 0 0", "rpy": "0 0 0"})
    ET.SubElement(inertial, "mass", {"value": "1e-8"})
    ET.SubElement(
        inertial,
        "inertia",
        {
            "ixx": "1e-12",
            "ixy": "0",
            "ixz": "0",
            "iyy": "1e-12",
            "iyz": "0",
            "izz": "1e-12",
        },
    )


def add_hand_specific_collision_proxies(
    robot: ET.Element, hand_id: str, side: str
) -> list[str]:
    """Add robust solid proxies where a source collision mesh is only a shell."""

    added: list[str] = []
    if hand_id == "tesollo_dg5f":
        palm_name = f"{'ll' if side == 'left' else 'rl'}_dg_palm"
        palm = next(
            (link for link in robot.findall("link") if link.get("name") == palm_name),
            None,
        )
        if palm is None:
            raise ValueError(f"{hand_id}/{side}: missing palm link {palm_name}")
        proxy_name = "collision_solid_palm_core"
        if not any(
            collision.get("name") == proxy_name
            for collision in palm.findall("collision")
        ):
            collision = ET.SubElement(palm, "collision", {"name": proxy_name})
            ET.SubElement(
                collision,
                "origin",
                {"xyz": "-0.0045 0 0.052", "rpy": "0 0 0"},
            )
            geometry = ET.SubElement(collision, "geometry")
            # This box remains inside the palm housing's mesh bounds.  The
            # source *_palm_c mesh is an open triangle shell, which can import
            # as a hollow dynamic collider and let the object pass through.
            ET.SubElement(geometry, "box", {"size": "0.045 0.055 0.07"})
            added.append(f"{palm_name}:{proxy_name}")
    return added


def normalize_urdf(
    source: Path,
    output: Path,
    hand_id: str,
    side: str,
) -> dict:
    robot = deepcopy(ET.parse(source).getroot())
    robot.set("name", f"{hand_id}_{side}_direct_motor")
    output.parent.mkdir(parents=True, exist_ok=True)

    removed_transmissions = remove_existing_transmissions(robot)
    inertia_repairs = sanitize_urdf_inertias(robot)
    joints = {
        joint.get("name"): joint
        for joint in robot.findall("joint")
        if joint.get("name")
    }
    movable = {
        name: joint
        for name, joint in joints.items()
        if scalar_dofs_urdf(joint.get("type", "fixed")) > 0
    }
    unsupported = [
        name
        for name, joint in movable.items()
        if scalar_dofs_urdf(joint.get("type", "fixed")) != 1
    ]
    if unsupported:
        raise ValueError(
            f"{hand_id}/{side}: planar/floating URDF joints require scalar expansion: {unsupported}"
        )

    flattened = flatten_mimics(movable)
    active_names = sorted(set(movable).difference(flattened))
    passive_names = sorted(flattened)

    collision_proxies = add_hand_specific_collision_proxies(
        robot, hand_id, side
    )

    records = []
    for name, joint in movable.items():
        lower, upper, effort, velocity, effort_source = joint_limit_values(joint)
        mimic = joint.find("mimic")
        if name in flattened:
            master, multiplier, offset = flattened[name]
            if mimic is None:
                mimic = ET.SubElement(joint, "mimic")
            mimic.attrib.clear()
            mimic.attrib.update(
                {
                    "joint": master,
                    "multiplier": f"{multiplier:.12g}",
                    "offset": f"{offset:.12g}",
                }
            )
            actuation = "passive_mimic"
        else:
            if mimic is not None:
                joint.remove(mimic)
            master, multiplier, offset = None, None, None
            add_simple_transmission(robot, name)
            actuation = "active_direct"
        records.append(
            {
                "joint": name,
                "type": joint.get("type"),
                "actuation": actuation,
                "master": master,
                "multiplier": multiplier,
                "offset": offset,
                "range": [lower, upper],
                "effort": effort,
                "velocity": velocity,
                "effort_source": effort_source,
            }
        )

    (
        mesh_references,
        missing_meshes,
        source_mesh_faces,
        output_mesh_faces,
    ) = materialize_urdf_meshes(robot, source.parent, output.parent)
    if missing_meshes:
        raise FileNotFoundError(
            f"{hand_id}/{side}: missing {len(missing_meshes)} meshes: {missing_meshes[:5]}"
        )
    add_mujoco_urdf_options(robot)
    ET.indent(robot, space="  ")
    ET.ElementTree(robot).write(output, encoding="utf-8", xml_declaration=True)

    return {
        "conversion": "urdf_direct_normalization",
        "source_path": str(source.relative_to(ROOT)),
        "output_path": str(output.relative_to(ROOT)),
        "source_transmissions_removed": removed_transmissions,
        "source_mimic_relations": len(flattened),
        "source_tendons_removed": 0,
        "source_equalities_removed": 0,
        "inertia_repairs": inertia_repairs,
        "collision_proxies_added": collision_proxies,
        "links": len(robot.findall("link")),
        "joints": len(robot.findall("joint")),
        "scalar_dofs": len(movable),
        "active_dofs": len(active_names),
        "passive_mimic_dofs": len(passive_names),
        "mesh_references": mesh_references,
        "generated_meshes": mesh_references,
        "source_mesh_faces": source_mesh_faces,
        "generated_mesh_faces": output_mesh_faces,
        "mesh_faces_preserved": source_mesh_faces == output_mesh_faces,
        "coupling_approximation": "exact_affine_mimic",
        "joint_records": records,
    }


def mj_joint_type(model: mujoco.MjModel, joint_id: int) -> str:
    value = int(model.jnt_type[joint_id])
    return {
        int(mujoco.mjtJoint.mjJNT_FREE): "free",
        int(mujoco.mjtJoint.mjJNT_BALL): "ball",
        int(mujoco.mjtJoint.mjJNT_SLIDE): "prismatic",
        int(mujoco.mjtJoint.mjJNT_HINGE): "revolute",
    }[value]


def mj_scalar_components(model: mujoco.MjModel, joint_id: int) -> list[dict]:
    kind = mj_joint_type(model, joint_id)
    name = (
        mujoco.mj_id2name(model, mujoco.mjtObj.mjOBJ_JOINT, joint_id)
        or f"joint_{joint_id}"
    )
    axis = np.asarray(model.jnt_axis[joint_id], dtype=float)
    limited = bool(model.jnt_limited[joint_id])
    original_range = np.asarray(model.jnt_range[joint_id], dtype=float)
    if kind in {"revolute", "prismatic"}:
        lower, upper = (
            original_range.tolist()
            if limited
            else (
                [-math.pi, math.pi]
                if kind == "revolute"
                else [-1.0, 1.0]
            )
        )
        return [
            {
                "name": name,
                "type": kind,
                "axis": axis.tolist(),
                "range": [float(lower), float(upper)],
                "source_joint_id": joint_id,
            }
        ]
    if kind == "ball":
        return [
            {
                "name": f"{name}__{suffix}",
                "type": "revolute",
                "axis": unit.tolist(),
                "range": [-math.pi, math.pi],
                "source_joint_id": joint_id,
            }
            for suffix, unit in zip("xyz", np.eye(3))
        ]
    if kind == "free":
        result = [
            {
                "name": f"{name}__t{suffix}",
                "type": "prismatic",
                "axis": unit.tolist(),
                "range": [-1.0, 1.0],
                "source_joint_id": joint_id,
            }
            for suffix, unit in zip("xyz", np.eye(3))
        ]
        result.extend(
            {
                "name": f"{name}__r{suffix}",
                "type": "revolute",
                "axis": unit.tolist(),
                "range": [-math.pi, math.pi],
                "source_joint_id": joint_id,
            }
            for suffix, unit in zip("xyz", np.eye(3))
        )
        return result
    raise ValueError(kind)


def mesh_from_mj_geom(model: mujoco.MjModel, geom_id: int) -> trimesh.Trimesh | None:
    geom_type = int(model.geom_type[geom_id])
    size = np.asarray(model.geom_size[geom_id], dtype=float)
    if geom_type == mujoco.mjtGeom.mjGEOM_MESH:
        mesh_id = int(model.geom_dataid[geom_id])
        vertex_start = int(model.mesh_vertadr[mesh_id])
        vertex_count = int(model.mesh_vertnum[mesh_id])
        face_start = int(model.mesh_faceadr[mesh_id])
        face_count = int(model.mesh_facenum[mesh_id])
        mesh = trimesh.Trimesh(
            vertices=np.asarray(
                model.mesh_vert[vertex_start : vertex_start + vertex_count],
                dtype=float,
            ).copy(),
            faces=np.asarray(
                model.mesh_face[face_start : face_start + face_count],
                dtype=np.int64,
            ).copy(),
            process=False,
        )
    elif geom_type == mujoco.mjtGeom.mjGEOM_BOX:
        mesh = trimesh.creation.box(extents=2.0 * size)
    elif geom_type == mujoco.mjtGeom.mjGEOM_SPHERE:
        mesh = trimesh.creation.icosphere(subdivisions=3, radius=float(size[0]))
    elif geom_type == mujoco.mjtGeom.mjGEOM_ELLIPSOID:
        mesh = trimesh.creation.icosphere(subdivisions=3, radius=1.0)
        mesh.apply_scale(size)
    elif geom_type == mujoco.mjtGeom.mjGEOM_CYLINDER:
        mesh = trimesh.creation.cylinder(
            radius=float(size[0]), height=2.0 * float(size[1]), sections=32
        )
    elif geom_type == mujoco.mjtGeom.mjGEOM_CAPSULE:
        mesh = trimesh.creation.capsule(
            radius=float(size[0]), height=2.0 * float(size[1]), count=[20, 20]
        )
    else:
        return None
    transform = np.eye(4)
    transform[:3, :3] = Rotation.from_quat(
        [
            model.geom_quat[geom_id][1],
            model.geom_quat[geom_id][2],
            model.geom_quat[geom_id][3],
            model.geom_quat[geom_id][0],
        ]
    ).as_matrix()
    transform[:3, 3] = np.asarray(model.geom_pos[geom_id], dtype=float)
    mesh.apply_transform(transform)
    mesh.remove_unreferenced_vertices()
    return mesh


def export_mjcf_body_meshes(
    model: mujoco.MjModel,
    body_id: int,
    mesh_dir: Path,
    body_name: str,
    use_visual_mesh_collision: bool = False,
) -> tuple[str | None, str | None, int]:
    geom_ids = list(
        range(
            int(model.body_geomadr[body_id]),
            int(model.body_geomadr[body_id] + model.body_geomnum[body_id]),
        )
    )
    explicit_visual = [
        geom_id for geom_id in geom_ids if int(model.geom_group[geom_id]) in {1, 2}
    ]
    visual_ids = explicit_visual or geom_ids
    if use_visual_mesh_collision:
        collision_ids = list(visual_ids)
    else:
        collision_ids = [
            geom_id
            for geom_id in geom_ids
            if int(model.geom_contype[geom_id]) != 0
            or int(model.geom_conaffinity[geom_id]) != 0
            or int(model.geom_group[geom_id]) == 3
        ]
        if not collision_ids:
            collision_ids = list(visual_ids)

    mesh_dir.mkdir(parents=True, exist_ok=True)

    def export(ids: list[int], suffix: str) -> tuple[str | None, int]:
        meshes = [
            mesh
            for geom_id in ids
            if (mesh := mesh_from_mj_geom(model, geom_id)) is not None
            and not mesh.is_empty
        ]
        if not meshes:
            return None, 0
        combined = trimesh.util.concatenate(meshes)
        combined.remove_unreferenced_vertices()
        path = mesh_dir / f"{safe_name(body_name)}_{suffix}.obj"
        combined.export(path, file_type="obj", include_normals=True, include_color=False)
        return path.name, int(len(combined.faces))

    visual_name, visual_faces = export(visual_ids, "visual")
    collision_name, _ = export(collision_ids, "collision")
    return visual_name, collision_name, visual_faces


def mjcf_couplings(model: mujoco.MjModel) -> tuple[
    dict[int, tuple[int, float, float, str]], set[int], list[dict]
]:
    """Return passive->(master, multiplier, offset, source), active IDs, audit."""
    active: set[int] = set()
    passive: dict[int, tuple[int, float, float, str]] = {}
    audit: list[dict] = []

    joint_transmission = int(mujoco.mjtTrn.mjTRN_JOINT)
    tendon_transmission = int(mujoco.mjtTrn.mjTRN_TENDON)
    tendon_actuators: list[tuple[int, int]] = []
    for actuator_id in range(model.nu):
        transmission = int(model.actuator_trntype[actuator_id])
        object_id = int(model.actuator_trnid[actuator_id][0])
        if transmission == joint_transmission:
            active.add(object_id)
        elif transmission == tendon_transmission:
            tendon_actuators.append((actuator_id, object_id))

    # MuJoCo joint equality: q_obj1 = data[0] + data[1] * q_obj2 + ...
    joint_equality = int(mujoco.mjtEq.mjEQ_JOINT)
    for equality_id in range(model.neq):
        if int(model.eq_type[equality_id]) != joint_equality:
            continue
        follower = int(model.eq_obj1id[equality_id])
        master = int(model.eq_obj2id[equality_id])
        coefficients = np.asarray(model.eq_data[equality_id][:5], dtype=float)
        if np.any(np.abs(coefficients[2:]) > 1.0e-10):
            raise ValueError(
                f"Nonlinear joint equality {equality_id} cannot become a URDF mimic: "
                f"{coefficients.tolist()}"
            )
        passive[follower] = (
            master,
            float(coefficients[1]),
            float(coefficients[0]),
            "mjcf_joint_equality",
        )
        active.add(master)
        audit.append(
            {
                "kind": "joint_equality",
                "master": master,
                "followers": [follower],
                "multipliers": [float(coefficients[1])],
                "offsets": [float(coefficients[0])],
                "loss": "none_linear",
            }
        )

    # Tendon dynamics are contact-dependent and cannot be represented exactly
    # by URDF mimic.  Use the last wrapped joint as the active (normally the
    # proximal Shadow joint) and map every follower through equal normalized
    # range fraction.  This preserves both endpoint ranges.
    joint_wrap = int(mujoco.mjtWrap.mjWRAP_JOINT)
    for actuator_id, tendon_id in tendon_actuators:
        joint_ids: list[int] = []
        for wrap_id in range(
            int(model.tendon_adr[tendon_id]),
            int(model.tendon_adr[tendon_id] + model.tendon_num[tendon_id]),
        ):
            if int(model.wrap_type[wrap_id]) == joint_wrap:
                joint_ids.append(int(model.wrap_objid[wrap_id]))
        if not joint_ids:
            raise ValueError(f"Tendon actuator {actuator_id} has no scalar joint wraps")
        master = joint_ids[-1]
        active.add(master)
        master_range = np.asarray(model.jnt_range[master], dtype=float)
        master_span = max(float(master_range[1] - master_range[0]), 1.0e-12)
        multipliers, offsets = [], []
        for follower in joint_ids[:-1]:
            follower_range = np.asarray(model.jnt_range[follower], dtype=float)
            multiplier = float(follower_range[1] - follower_range[0]) / master_span
            offset = float(follower_range[0] - multiplier * master_range[0])
            passive[follower] = (
                master,
                multiplier,
                offset,
                "mjcf_tendon_range_fit",
            )
            multipliers.append(multiplier)
            offsets.append(offset)
        audit.append(
            {
                "kind": "tendon",
                "tendon_id": tendon_id,
                "actuator_id": actuator_id,
                "master": master,
                "followers": joint_ids[:-1],
                "multipliers": multipliers,
                "offsets": offsets,
                "loss": "contact_dependent_differential_removed",
            }
        )

    for follower in passive:
        active.discard(follower)
    # No loose passive DoF is permitted: every remaining joint is promoted to
    # an independent active direct motor.
    active.update(set(range(model.njnt)).difference(passive))
    return passive, active, audit


def mjcf_effort_velocity(
    model: mujoco.MjModel,
    joint_id: int,
    actuator_ids: list[int],
    joint_range: tuple[float, float],
    kind: str,
) -> tuple[float, float, str]:
    if bool(model.jnt_actfrclimited[joint_id]):
        values = np.asarray(model.jnt_actfrcrange[joint_id], dtype=float)
        effort = max(abs(float(values[0])), abs(float(values[1])))
        effort_source = "mjcf_joint_actuator_force_range"
    else:
        limited_efforts = []
        stiffness_proxies = []
        for actuator_id in actuator_ids:
            if bool(model.actuator_forcelimited[actuator_id]):
                force_range = np.asarray(model.actuator_forcerange[actuator_id], dtype=float)
                force = max(abs(float(force_range[0])), abs(float(force_range[1])))
                gear = abs(float(model.actuator_gear[actuator_id][0]))
                limited_efforts.append(force * max(gear, 1.0e-12))
            else:
                kp = abs(float(model.actuator_gainprm[actuator_id][0]))
                span = max(float(joint_range[1] - joint_range[0]), 0.1)
                if kp > 0:
                    stiffness_proxies.append(kp * span)
        if limited_efforts:
            effort = max(limited_efforts)
            effort_source = "mjcf_actuator_force_range"
        elif stiffness_proxies:
            effort = float(np.clip(max(stiffness_proxies), 0.1, 1000.0))
            effort_source = "mjcf_stiffness_times_range_proxy"
        else:
            effort = DEFAULT_EFFORT
            effort_source = "default"
    span = max(float(joint_range[1] - joint_range[0]), 0.1)
    velocity = (
        min(max(4.0 * span, 0.1), 4.0)
        if kind == "prismatic"
        else min(max(4.0 * span, 1.0), 20.0)
    )
    return effort, velocity, effort_source


def normalize_mjcf(
    source: Path,
    output: Path,
    hand_id: str,
    side: str,
) -> dict:
    model = mujoco.MjModel.from_xml_path(str(source))
    passive, active, coupling_records = mjcf_couplings(model)

    robot = ET.Element("robot", {"name": f"{hand_id}_{side}_direct_motor"})
    ET.SubElement(robot, "link", {"name": "world"})
    output.parent.mkdir(parents=True, exist_ok=True)
    mesh_dir = output.parent / "meshes"
    if mesh_dir.exists():
        shutil.rmtree(mesh_dir)

    body_names = {
        body_id: (
            mujoco.mj_id2name(model, mujoco.mjtObj.mjOBJ_BODY, body_id)
            or f"body_{body_id}"
        )
        for body_id in range(1, model.nbody)
    }
    final_link: dict[int, str] = {0: "world"}
    joint_name_for_source: dict[int, str] = {}
    source_joint_records: list[dict] = []
    generated_meshes = 0
    total_faces = 0

    actuator_by_joint: dict[int, list[int]] = defaultdict(list)
    for actuator_id in range(model.nu):
        if int(model.actuator_trntype[actuator_id]) == int(mujoco.mjtTrn.mjTRN_JOINT):
            actuator_by_joint[int(model.actuator_trnid[actuator_id][0])].append(actuator_id)
    for coupling in coupling_records:
        if coupling["kind"] == "tendon":
            actuator_by_joint[int(coupling["master"])].append(int(coupling["actuator_id"]))

    for body_id in range(1, model.nbody):
        body_name = body_names[body_id]
        actual_link_name = safe_name(body_name)
        ET.SubElement(robot, "link", {"name": actual_link_name})
        final_link[body_id] = actual_link_name

        mass = float(model.body_mass[body_id])
        if mass > 0:
            link = robot.findall("link")[-1]
            inertial = ET.SubElement(link, "inertial")
            ET.SubElement(
                inertial,
                "origin",
                {
                    "xyz": fmt(model.body_ipos[body_id]),
                    "rpy": fmt(quat_wxyz_to_rpy(model.body_iquat[body_id])),
                },
            )
            ET.SubElement(inertial, "mass", {"value": f"{mass:.12g}"})
            inertia = np.asarray(model.body_inertia[body_id], dtype=float)
            ET.SubElement(
                inertial,
                "inertia",
                {
                    "ixx": f"{inertia[0]:.12g}",
                    "ixy": "0",
                    "ixz": "0",
                    "iyy": f"{inertia[1]:.12g}",
                    "iyz": "0",
                    "izz": f"{inertia[2]:.12g}",
                },
            )

        visual_mesh, collision_mesh, faces = export_mjcf_body_meshes(
            model,
            body_id,
            mesh_dir,
            body_name,
            use_visual_mesh_collision=hand_id in VISUAL_MESH_COLLISION_HANDS,
        )
        total_faces += faces
        link = robot.findall("link")[-1]
        if visual_mesh:
            visual = ET.SubElement(link, "visual", {"name": f"{actual_link_name}_visual"})
            geometry = ET.SubElement(visual, "geometry")
            ET.SubElement(
                geometry,
                "mesh",
                {"filename": f"meshes/{visual_mesh}"},
            )
            generated_meshes += 1
        if collision_mesh:
            collision = ET.SubElement(
                link, "collision", {"name": f"{actual_link_name}_collision"}
            )
            geometry = ET.SubElement(collision, "geometry")
            ET.SubElement(
                geometry,
                "mesh",
                {"filename": f"meshes/{collision_mesh}"},
            )
            generated_meshes += 1

        parent_id = int(model.body_parentid[body_id])
        parent_link = final_link[parent_id]
        body_translation = np.asarray(model.body_pos[body_id], dtype=float)
        body_rotation = quat_wxyz_to_rpy(model.body_quat[body_id])
        start = int(model.body_jntadr[body_id])
        count = int(model.body_jntnum[body_id])
        component_records: list[dict] = []
        for joint_id in range(start, start + count):
            component_records.extend(mj_scalar_components(model, joint_id))

        if not component_records:
            joint = ET.SubElement(
                robot,
                "joint",
                {"name": f"fixed__{actual_link_name}", "type": "fixed"},
            )
            ET.SubElement(joint, "parent", {"link": parent_link})
            ET.SubElement(joint, "child", {"link": actual_link_name})
            ET.SubElement(
                joint,
                "origin",
                {"xyz": fmt(body_translation), "rpy": fmt(body_rotation)},
            )
            continue

        current_parent = parent_link
        for component_index, component in enumerate(component_records):
            is_last = component_index == len(component_records) - 1
            child_link = (
                actual_link_name
                if is_last
                else f"virtual__{actual_link_name}__{component_index:02d}"
            )
            if not is_last:
                virtual_link = ET.SubElement(robot, "link", {"name": child_link})
                add_negligible_virtual_inertial(virtual_link)
            joint_name = safe_name(component["name"])
            if joint_name in {
                node.get("name") for node in robot.findall("joint")
            }:
                joint_name = f"{joint_name}__{body_id}_{component_index}"
            joint = ET.SubElement(
                robot,
                "joint",
                {"name": joint_name, "type": component["type"]},
            )
            ET.SubElement(joint, "parent", {"link": current_parent})
            ET.SubElement(joint, "child", {"link": child_link})
            ET.SubElement(
                joint,
                "origin",
                {
                    "xyz": fmt(body_translation if component_index == 0 else np.zeros(3)),
                    "rpy": fmt(body_rotation if component_index == 0 else np.zeros(3)),
                },
            )
            ET.SubElement(joint, "axis", {"xyz": fmt(component["axis"])})
            source_joint_id = int(component["source_joint_id"])
            lower, upper = component["range"]
            effort, velocity, effort_source = mjcf_effort_velocity(
                model,
                source_joint_id,
                actuator_by_joint[source_joint_id],
                (lower, upper),
                component["type"],
            )
            ET.SubElement(
                joint,
                "limit",
                {
                    "lower": f"{lower:.12g}",
                    "upper": f"{upper:.12g}",
                    "effort": f"{effort:.12g}",
                    "velocity": f"{velocity:.12g}",
                },
            )
            dof_address = int(model.jnt_dofadr[source_joint_id])
            dynamics = ET.SubElement(
                joint,
                "dynamics",
                {
                    "damping": f"{float(model.dof_damping[dof_address]):.12g}",
                    "friction": f"{float(model.dof_frictionloss[dof_address]):.12g}",
                },
            )
            del dynamics
            joint_name_for_source.setdefault(source_joint_id, joint_name)
            component["urdf_joint_name"] = joint_name
            component["effort"] = effort
            component["velocity"] = velocity
            component["effort_source"] = effort_source
            source_joint_records.append(component)
            current_parent = child_link

    # Apply active/passive classification after every source joint has a URDF
    # name.  Ball/free expansion is promoted active component-wise; none of the
    # current coupled sources uses a multi-scalar coupled joint.
    for record in source_joint_records:
        source_joint_id = int(record["source_joint_id"])
        joint_name = record["urdf_joint_name"]
        joint = next(
            node for node in robot.findall("joint") if node.get("name") == joint_name
        )
        if source_joint_id in passive:
            master_id, multiplier, offset, coupling_source = passive[source_joint_id]
            if master_id not in joint_name_for_source:
                raise ValueError(f"Missing active mimic master {master_id}")
            ET.SubElement(
                joint,
                "mimic",
                {
                    "joint": joint_name_for_source[master_id],
                    "multiplier": f"{multiplier:.12g}",
                    "offset": f"{offset:.12g}",
                },
            )
            record.update(
                {
                    "actuation": "passive_mimic",
                    "master": joint_name_for_source[master_id],
                    "multiplier": multiplier,
                    "offset": offset,
                    "coupling_source": coupling_source,
                }
            )
        else:
            if source_joint_id not in active:
                raise ValueError(f"Loose movable joint {joint_name}")
            add_simple_transmission(robot, joint_name)
            record.update(
                {
                    "actuation": "active_direct",
                    "master": None,
                    "multiplier": None,
                    "offset": None,
                    "coupling_source": "direct_or_promoted",
                }
            )

    add_mujoco_urdf_options(robot)
    ET.indent(robot, space="  ")
    ET.ElementTree(robot).write(output, encoding="utf-8", xml_declaration=True)
    active_dofs = sum(
        record["actuation"] == "active_direct" for record in source_joint_records
    )
    passive_dofs = sum(
        record["actuation"] == "passive_mimic" for record in source_joint_records
    )
    return {
        "conversion": "mjcf_to_direct_urdf",
        "source_path": str(source.relative_to(ROOT)),
        "output_path": str(output.relative_to(ROOT)),
        "source_transmissions_removed": int(model.nu),
        "source_mimic_relations": 0,
        "source_tendons_removed": int(model.ntendon),
        "source_equalities_removed": int(model.neq),
        "links": len(robot.findall("link")),
        "joints": len(robot.findall("joint")),
        "source_bodies": int(model.nbody - 1),
        "source_scalar_dofs": int(model.nv),
        "scalar_dofs": len(source_joint_records),
        "active_dofs": active_dofs,
        "passive_mimic_dofs": passive_dofs,
        "mesh_references": generated_meshes,
        "generated_meshes": generated_meshes,
        "generated_visual_faces": total_faces,
        "collision_geometry": (
            "visual_mesh"
            if hand_id in VISUAL_MESH_COLLISION_HANDS
            else "source"
        ),
        "coupling_approximation": (
            "range-normalized affine mimic for tendons"
            if model.ntendon
            else "exact affine mimic for joint equalities"
            if model.neq
            else "none"
        ),
        "coupling_records": coupling_records,
        "joint_records": source_joint_records,
    }


def output_audit(path: Path) -> dict:
    robot = ET.parse(path).getroot()
    links = {link.get("name") for link in robot.findall("link")}
    joints = robot.findall("joint")
    children = {
        child.get("link")
        for joint in joints
        if (child := joint.find("child")) is not None
    }
    roots = links.difference(children)
    transmissions = {
        joint.get("name")
        for transmission in robot.findall("transmission")
        if (joint := transmission.find("joint")) is not None
    }
    active, passive, loose = [], [], []
    ranges: dict[str, list[float]] = {}
    missing_meshes: list[str] = []
    for mesh in robot.iter("mesh"):
        filename = mesh.get("filename")
        if filename and not (path.parent / filename).resolve().exists():
            missing_meshes.append(filename)
    for joint in joints:
        name = joint.get("name")
        kind = joint.get("type", "fixed")
        if scalar_dofs_urdf(kind) == 0:
            continue
        mimic = joint.find("mimic")
        if mimic is not None:
            passive.append(name)
            if name in transmissions:
                loose.append(f"{name}: passive joint has transmission")
            master = mimic.get("joint")
            if master not in transmissions:
                loose.append(f"{name}: mimic master {master} is not active")
        elif name in transmissions:
            active.append(name)
        else:
            loose.append(f"{name}: movable joint is neither active nor mimic")
        limit = joint.find("limit")
        if kind != "continuous":
            if limit is None or limit.get("lower") is None or limit.get("upper") is None:
                loose.append(f"{name}: range missing")
            else:
                ranges[name] = [
                    float(limit.get("lower")),
                    float(limit.get("upper")),
                ]
    return {
        "roots": sorted(roots),
        "links": len(links),
        "joints": len(joints),
        "scalar_dofs": len(active) + len(passive),
        "active_dofs": len(active),
        "passive_mimic_dofs": len(passive),
        "loose_or_invalid_dofs": loose,
        "missing_meshes": missing_meshes,
        "ranges": ranges,
    }


def choose_source(hand_id: str, side: str, entry: dict) -> tuple[str, Path]:
    source_format = entry["format"]
    source = (ASSETS / entry["path"]).resolve()
    if source_format == "usd":
        companion = URDF_COMPANIONS.get(hand_id, {}).get(side)
        if companion is None or not companion.exists():
            raise ValueError(
                f"{hand_id}/{side}: USD-only input requires an explicit URDF companion"
            )
        return "urdf", companion.resolve()
    return source_format, source


def build_all(clean: bool = True) -> dict:
    source_registry = json.loads(REGISTRY.read_text(encoding="utf-8"))
    if clean and OUTPUT_ROOT.exists():
        shutil.rmtree(OUTPUT_ROOT)
    OUTPUT_ROOT.mkdir(parents=True, exist_ok=True)

    output_registry = {
        "schema_version": 1,
        "actuation_schema": {
            "active": "independent scalar direct motor with SimpleTransmission",
            "passive": "affine mimic joint of one active master",
            "forbidden": [
                "unconstrained passive movable joint",
                "tendon actuator",
                "nonlinear linkage",
                "mimic chain",
            ],
        },
        "hands": {},
    }
    audit_entries = []
    for hand_id, metadata in source_registry["hands"].items():
        output_registry["hands"][hand_id] = {
            "display_name": metadata["display_name"],
            "source": metadata.get("source"),
            "entries": {},
        }
        for side in SIDES:
            entry = metadata["entries"][side]
            source_format, source = choose_source(hand_id, side, entry)
            output = OUTPUT_ROOT / hand_id / side / "hand.urdf"
            print(
                f"[{hand_id:20s} {side:5s}] {source_format.upper()} -> URDF",
                flush=True,
            )
            if source_format == "urdf":
                conversion = normalize_urdf(source, output, hand_id, side)
            elif source_format == "mjcf":
                conversion = normalize_mjcf(source, output, hand_id, side)
            else:
                raise ValueError(
                    f"{hand_id}/{side}: unsupported direct conversion source {source_format}"
                )
            audit = output_audit(output)
            if audit["roots"] != ["world"] and len(audit["roots"]) != 1:
                raise ValueError(f"{hand_id}/{side}: invalid roots {audit['roots']}")
            if audit["loose_or_invalid_dofs"]:
                raise ValueError(
                    f"{hand_id}/{side}: {audit['loose_or_invalid_dofs']}"
                )
            if audit["missing_meshes"]:
                raise FileNotFoundError(
                    f"{hand_id}/{side}: missing meshes {audit['missing_meshes'][:5]}"
                )
            if audit["scalar_dofs"] != conversion["scalar_dofs"]:
                raise ValueError(
                    f"{hand_id}/{side}: conversion/audit DoF mismatch "
                    f"{conversion['scalar_dofs']} != {audit['scalar_dofs']}"
                )
            conversion["output_audit"] = audit
            audit_entries.append(
                {
                    "hand_id": hand_id,
                    "side": side,
                    **conversion,
                }
            )
            output_registry["hands"][hand_id]["entries"][side] = {
                "format": "urdf",
                "path": str(output.relative_to(ASSETS)),
                "active_dofs": audit["active_dofs"],
                "passive_mimic_dofs": audit["passive_mimic_dofs"],
                "scalar_dofs": audit["scalar_dofs"],
                "collision_geometry": (
                    "visual_mesh"
                    if hand_id in VISUAL_MESH_COLLISION_HANDS
                    else "source"
                ),
                "source_format": entry["format"],
                "source_path": entry["path"],
            }

    summary = {
        "hands": len(output_registry["hands"]),
        "assets": len(audit_entries),
        "active_dofs": sum(entry["active_dofs"] for entry in audit_entries),
        "passive_mimic_dofs": sum(
            entry["passive_mimic_dofs"] for entry in audit_entries
        ),
        "scalar_dofs": sum(entry["scalar_dofs"] for entry in audit_entries),
        "assets_with_changes": sum(
            bool(
                entry["source_tendons_removed"]
                or entry["source_equalities_removed"]
                or entry["source_mimic_relations"]
                or entry["conversion"] == "mjcf_to_direct_urdf"
            )
            for entry in audit_entries
        ),
        "loose_passive_dofs": sum(
            len(entry["output_audit"]["loose_or_invalid_dofs"])
            for entry in audit_entries
        ),
        "missing_meshes": sum(
            len(entry["output_audit"]["missing_meshes"])
            for entry in audit_entries
        ),
    }
    output_registry["summary"] = summary
    OUTPUT_REGISTRY.write_text(
        json.dumps(output_registry, indent=2) + "\n", encoding="utf-8"
    )
    AUDIT_PATH.write_text(
        json.dumps(
            {
                "schema_version": 1,
                "summary": summary,
                "entries": audit_entries,
            },
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )
    README_PATH.write_text(DIRECT_MOTOR_README, encoding="utf-8")
    print(json.dumps(summary, indent=2))
    return summary


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--no-clean",
        action="store_true",
        help="Keep existing generated files before rebuilding",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    build_all(clean=not args.no_clean)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
